name: test_server
on:
  workflow_dispatch:
  push:
    paths:
      - server/**
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: cd server && poetry install --no-interaction
      - name: Run tests
        run: cd server && ./scripts/run_tests.sh
